package constants

const (
	ErrorConfig                 = "Error while loading config"
	InternalServerError         = "Internal Server error. Please check"
	InvalidCharacterError       = "invalid character"
	ErrorFetchingSchema         = "Error fetching schema"
	ErrorFetchingConfig         = "Error fetching config"
	EmptyServiceUrl             = "Empty service url found"
	ErrorFetchingTopic          = "Error fetching topic: %s details"
	ErrorTopicNotFound          = "Topic: %s not found"
	AppEventNameNotFound        = "App name or event name not found. Please check"
	ErrorLoadingTopicFromCache  = "Error loading topic from cache, check logs for more details"
	ErrPlainEventDataError      = "Unsupported type error. Event data should be a string type"
	TopicUnsubscribed           = "Topic is not subscribed. Please subscribe to topic first"
	ErrUnidentifiedSchema       = "Unidentified schema found. Please check schema type"
	ErrorSchemaNotFound         = "Error Schema not found for your event"
	ErrorValidatingSchema       = "Error validating schema. Please check you topic schema"
	InvalidData                 = "Your event data doesn't match topic schema. Please check logs for validation report"
	HostPortNotFound            = "Hostname or port not found. Please check"
	ErrorFetchingConsumerEntity = "Error fetching consumer entity"
	ErrorFetchingOffsetEntity   = "ErrorFetchingOffsetEntity"
	ErrorAppNameNotFound        = "Error AppName not found"
	ErrorEmptyEventListeners    = "Error empty event listener list. Invalid consumer config"
	ConsumerNotRegistered       = "Consumer with appname: %s not registered. Please register the consumer at airbus first"
	ConsumerEventNotRegistered  = "Consumer event with appname: %s and topic: %v not registered. Please register the event first"
	ErrorConsumerCache          = "Consumer cache entry doesn't exist for event"
	ErrorSubscribeEvent         = "Error in handling SubscribeEvent: %+v, error: %s\n"
	ErrorUnsubscribeEvent       = "Error in handling UnsubscribeEvent: %+v, error: %s\n"
	ErrorMetadataAirbus         = "Error in metadata airbus handler: %s\n"
	NilConsumer                 = "Nil consumer, terminating"
	SyncProducerError           = "You are using a sync producer. Please call SyncSend method"
	AsyncProducerError          = "You are using an async producer. Please call AsyncSend method"
	InvalidSchemaError          = "Invalid Schema. Please check your schema"
	ErrorOffsetConfigNotFound   = "offset config not found for given consumer group"
	ErrorFetchingOffsetEntry    = "error found while fetching offset entry form servcie "
	ErrorFetchingClusterEntry   = "error found while fetching cluster entry form servcie "
)
